"""Add qr_code_image to Product

Revision ID: 28355be61292
Revises: 8f3bf8ac97f9
Create Date: 2025-04-23 21:41:35.222849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28355be61292'
down_revision = '8f3bf8ac97f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('sketchfab_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sketchfab_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('qr_code_image')

    # ### end Alembic commands ###
