"""empty message

Revision ID: 30ccb9131b12
Revises: eb466ef0a231
Create Date: 2025-01-31 20:49:41.345885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ccb9131b12'
down_revision = 'eb466ef0a231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_delivery_person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['assigned_delivery_person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_delivery_person_id')

    # ### end Alembic commands ###
