"""Add model_file to Product

Revision ID: 8f3bf8ac97f9
Revises: 4c07525dd840
Create Date: 2025-04-13 19:58:03.696041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3bf8ac97f9'
down_revision = '4c07525dd840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('model_file')

    # ### end Alembic commands ###
