"""Removed dob column from User model

Revision ID: 9280d9e35228
Revises: 9912c8cbb1e3
Create Date: 2025-02-18 22:59:29.495493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9280d9e35228'
down_revision = '9912c8cbb1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('Pending', 'In Transit', 'Delivered', 'Failed'),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('gender')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=False))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Pending', 'In Transit', 'Delivered', 'Failed'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
