"""empty message

Revision ID: 9912c8cbb1e3
Revises: 30ccb9131b12
Create Date: 2025-01-31 20:51:38.697300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9912c8cbb1e3'
down_revision = '30ccb9131b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_delivery_person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('d_id', 'user', ['assigned_delivery_person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_constraint('d_id', type_='foreignkey')
        batch_op.drop_column('assigned_delivery_person_id')

    # ### end Alembic commands ###
