"""Remove contact column from User table

Revision ID: b25d2c356b13
Revises: 9280d9e35228
Create Date: 2025-03-21 12:30:36.159911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25d2c356b13'
down_revision = '9280d9e35228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('contact')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), nullable=False))

    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('payment_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('signature', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###
