"""empty message

Revision ID: eb466ef0a231
Revises: a550e1a95b81
Create Date: 2025-01-28 22:25:07.476515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb466ef0a231'
down_revision = 'a550e1a95b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('Delivered_Date')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_rating', sa.Float(), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.FLOAT(), nullable=True))
        batch_op.drop_column('avg_rating')

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Delivered_Date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('delivered_date')

    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_details_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('order_amount', sa.FLOAT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['order_details_id'], ['order_details.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
